"""
Code for allowing calendar subscription

Note that these are public routes, so are managed by tokens generated by logged in users.
"""

import datetime
import logging
from typing import List
from zoneinfo import ZoneInfo

from attr import define
from flask import Blueprint, Response, abort, request, url_for
from icalendar import Calendar
from icalendar import Event as ICalEvent

from mountains.context import db_conn
from mountains.models.events import Event, attendees_repo, events_repo
from mountains.models.tokens import tokens_ics_repo
from mountains.models.users import users_repo

blueprint = Blueprint("ics", __name__, url_prefix="/ics")
logger = logging.getLogger(__name__)


@blueprint.route("/calendar.ics")
def calendar():
    """
    Returns the calendar for all events (from 1 month before today)
    """
    _user_id_from_token_or_401()
    date_cut_off = (datetime.date.today() - datetime.timedelta(days=31)).strftime(
        "%Y-%m-%d"
    )
    with db_conn() as conn:
        events = [
            _EventWithIsWaitingList(event=event, is_waiting_list=False)
            for event in events_repo(conn).list_where(
                is_deleted=False, is_draft=False, event_dt=(">", date_cut_off)
            )
        ]
    return _ics_response(
        name="All CMC Events",
        events=events,
        description="All upcoming club events",
    )


@blueprint.route("/user-calendar.ics")
def user_calendar():
    """
    Returns the calendar for all events this user has been to
    """
    user_id = _user_id_from_token_or_401()
    with db_conn() as conn:
        user_events = [
            _EventWithIsWaitingList(event=event, is_waiting_list=att.is_waiting_list)
            for att in attendees_repo(conn).list_where(user_id=user_id)
            if (event := events_repo(conn).get(id=att.event_id)) is not None
        ]
    return _ics_response(
        name="My CMC Events",
        events=user_events,
        description="Upcoming club events you are attending or wait-listed for",
    )


def _user_id_from_token_or_401() -> int:
    token_str = request.args.get("token")
    if not token_str:
        abort(401)
    with db_conn() as conn:
        token_repo = tokens_ics_repo(conn)
        token = token_repo.get(id=token_str)
        if token is None:
            abort(401)
        user = users_repo(conn).get(id=token.user_id)
        if user is None:
            logger.warning("Removing token for missing user ID: {user_id}")
            token_repo.delete_where(id=token_str)
            abort(401)
    return user.id


@define
class _EventWithIsWaitingList:
    event: Event
    is_waiting_list: bool


def _ics_response(
    name: str, events: List[_EventWithIsWaitingList], description: str | None = None
) -> Response:
    london = ZoneInfo("Europe/London")
    cal = Calendar()
    cal.add("prodid", f"-//clydemc.org//{name}")
    cal.add("version", "2.0")
    cal.add("X-WR-TIMEZONE", "Europe/London")
    cal.add("X-WR-CALNAME", name)
    if description:
        cal.add("X-WR-CALDESC", description)

    for e in events:
        event = e.event
        ical_event = ICalEvent()
        ical_event.add("uid", f"org.clydemc.event.{event.id}")
        if e.is_waiting_list:
            ical_event.add("summary", f"WAIT LIST - {event.title}")
        else:
            ical_event.add("summary", event.title)
        start_london = event.event_dt.astimezone(london)
        ical_event.add("dtstart", start_london)
        if event.event_end_dt is not None:
            end_london = event.event_end_dt.astimezone(london)
            ical_event.add("dtend", end_london)
        else:
            ical_event.add("duration", datetime.timedelta(hours=2))
        ical_event.add(
            "url", url_for("platform.events.event", id=event.id, _external=True)
        )
        ical_event.add("dtstamp", event.created_on_utc)
        ical_event.add("last-modified", event.updated_on_utc)
        cal.add_component(ical_event)
    cal.add_missing_timezones()
    return Response(
        cal.to_ical(),
        mimetype="text/calendar; charset=utf-8",
        headers={"Content-Disposition": "inline"},
    )
